# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'WindmillsAmsterdam' do
	pod 'Firebase'
	pod 'GoogleMaps'
    pod 'HockeySDK'
end

target 'WindmillsAmsterdamTests' do

end

target 'WindmillsAmsterdamUITests' do

end
