# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'WindmillsAmsterdam' do

    # Firebase stuff
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'GoogleMaps'
    pod 'AGi18n'
end

target 'WindmillsAmsterdamTests' do

end

target 'WindmillsAmsterdamUITests' do

end
